# Copyright 2026, Versioneer (https://versioneer.at)
# SPDX-License-Identifier: Apache-2.0

name: PR

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main

permissions:
  contents: read

jobs:
  static:
    name: Pre-commit and docs
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Set up uv
        uses: astral-sh/setup-uv@v6

      - name: Install project dependencies
        run: uv sync --all-groups --frozen

      - name: Run pre-commit hooks
        run: make pre-commit

      - name: Build docs
        run: make docs

  unit:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Set up uv
        uses: astral-sh/setup-uv@v6

      - name: Install project dependencies
        run: uv sync --all-groups --frozen

      - name: Run unit tests
        run: make test-unit

  integration:
    name: Integration tests
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Set up uv
        uses: astral-sh/setup-uv@v6

      - name: Install project dependencies
        run: uv sync --all-groups --frozen

      - name: Run integration tests
        run: make test-integration

  e2e:
    name: End-to-end and performance tests
    runs-on: ubuntu-latest
    needs:
      - static
      - unit
      - integration
    steps:
      - name: Clone the code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Set up uv
        uses: astral-sh/setup-uv@v6

      - name: Install project dependencies
        run: uv sync --all-groups --frozen

      - name: Set up kind cluster
        uses: helm/kind-action@v1
        with:
          cluster_name: stacpkg-s3-store

      - name: Run all end-to-end and performance tests
        run: make test-e2e-full
